server:
  port: 8300
spring:
  profiles:
    active: @profile.active@
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace