spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
          # 轉發 ClusterIP 關鍵 (若都是 NodePort 就不需要這段？)
          url-expression: "'http://'+serviceId+':'+port"