server:
  port: 8200
spring:
  application:
    name: backend-server
  profiles:
    active: @profile.active@
management:
  endpoints:
    web:
      exposure:
        include: '*'
k8s:
  api:
    service-id: k8s-api-service